opam: &OPAM
  language: minimal
  sudo: required
  services: docker
  install: |
    # Prepare the COQ container
    docker pull ${COQ_IMAGE}
    docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
    docker exec COQ /bin/bash --login -c "
      # This bash script is double-quoted to interpolate Travis CI env vars:
      echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex  # -e = exit on failure; -x = trace for debug
      opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
      opam update -y
      opam pin add ${CONTRIB_NAME} . -y -n -k path
      opam install ${CONTRIB_NAME} -y -j ${NJOBS} --deps-only
      opam config list
      opam repo list
      opam list
      "
  script:
  - echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex
      sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
      opam install ${CONTRIB_NAME} -v -y -j ${NJOBS}
      "
  - docker stop COQ  # optional
  - echo -en 'travis_fold:end:script\\r'

matrix:
  include:

  # Test supported versions of Coq via OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.9
    - CONTRIB_NAME=coq-verdi
    - NJOBS=2
    <<: *OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:8.10
    - CONTRIB_NAME=coq-verdi
    - NJOBS=2
    <<: *OPAM
  - env:
    - COQ_IMAGE=coqorg/coq:dev
    - CONTRIB_NAME=coq-verdi
    - NJOBS=2
    <<: *OPAM
