language: c
script: bash -ex .travis-ci.sh
sudo: false
env:
  global:
    - VERDI_RAFT_BRANCH=master
  matrix:
    - DOWNSTREAM=none
    - DOWNSTREAM=verdi-raft
before_install:
  - openssl aes-256-cbc -K $encrypted_130bc391cda8_key -iv $encrypted_130bc391cda8_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
  - cp .travis/travis_rsa ~/.ssh
  - chmod 600 ~/.ssh/travis_rsa
  - cp .travis/ssh_config ~/.ssh/config
notifications:
  slack:
    on_start: always
    rooms:
      - secure: QNV6vNowWxm2I9HkiZWSMvzuCF0IZ0DkOtrSjSeca2HhSZ5tmk7/bo6Yg21+ADJzoFeiFGqV8Zs+5BAZDDWik9DO6yS5IFPPqtQAtiHy5xeVjjfZtdBLgGnDBkCGyIcJCsM9f3x6H6atnLTs2u3LGqhsL0+AJULXteNRQ03XiU0=
